<a href="https://colab.research.google.com/github/PhonxayMax/Math-and-Architectures-of-Deep-Learning/blob/main/CH7_7_2_3_perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch



def fully_connected_layer(X, W, b, activation=None):
    """
    Implements a Fully Connected layer of Neural Networks
    Input:
    1) X: n x d tensor - each row of X is an input vector, there are n vectors
          each of size d.
    2) W: m x d tensor
    Returns:
    y: m tensor, y = W X.transpose + b
    """
    assert (activation is None or activation is torch.sigmoid or activation is torch.relu
            or activation is torch.tanh or activation is torch.heaviside)
    assert torch.is_tensor(X) and torch.is_tensor(W) and torch.is_tensor(b)
    assert len(X.shape) == 2
    n = X.shape[0]  # number of input vectors
    d = X.shape[1]  # input  dimensionality
    m = b.shape[0]  # output dimensionality
    assert b.shape == torch.Size([m]), "b.shape = {}".format(b.shape)
    assert W.shape == torch.Size([m, d]), "W.shape = {}".format(W.shape)

    X = torch.cat((X, torch.ones([X.shape[0], 1], dtype=torch.float32)), dim=1)
    W = torch.cat((W, b.unsqueeze(dim=1)), dim=1)
    y = torch.matmul(W, X.transpose(0, 1))
    if activation is not None:
        if activation is torch.heaviside:
            y = activation(y, torch.tensor(1.0))
        else:
            y = activation(y)

    return y.transpose(0, 1)


def Perceptron(X, W, b, activation=torch.heaviside):
    assert W.shape[0] == 1 and b.shape[0] == 1
    return fully_connected_layer(X, W, b, activation=activation)


def MLP(X, W0, W1, b0, b1, activation0=torch.heaviside, activation1=None):
    y0 = fully_connected_layer(X=X, W=W0, b=b0, activation=activation0)
    return fully_connected_layer(X=y0, W=W1, b=b1, activation=activation1)

#Prompton ChatGPT ---> X is an input tensor with n data samples, each of dimension d, gives me 5 examples of this

In [3]:
"""
ตัวอย่างที่ 1: Input ของ Perceptron ที่มี 4 ตัวอย่างข้อมูล (n = 4) และแต่ละตัวอย่างมี 2 ฟีเจอร์ (d = 2) ดังนี้
"""
# n = 4, d = 2
X = torch.tensor([
    [1.2, 0.7],
    [3.5, 1.1],
    [0.0, 2.2],
    [1.8, 3.0]
])
X

tensor([[1.2000, 0.7000],
        [3.5000, 1.1000],
        [0.0000, 2.2000],
        [1.8000, 3.0000]])

In [5]:
"""
ตัวอย่างที่ 2: ข้อมูลภาพ (flattened) 3 ภาพ ขนาด 2 × 2 (d = 4) จากนั้นสร้าง input tensor สำหรับ Perceptron ที่มี 3 ตัวอย่างข้อมูล (n = 3) และแต่ละตัวอย่างมี 4 ฟีเจอร์ (d = 4)
"""
# n = 3, d = 2x2
X = torch.tensor([
    [0.0, 0.2, 0.1, 0.3],
    [1.0, 0.9, 0.8, 0.7],
    [0.5, 0.6, 0.6, 0.5]
])
X

tensor([[0.0000, 0.2000, 0.1000, 0.3000],
        [1.0000, 0.9000, 0.8000, 0.7000],
        [0.5000, 0.6000, 0.6000, 0.5000]])

In [9]:
"""
 ตัวอย่างที่ 3: ข้อมูลเชิงเวลา (Time series) จาก 5 ตัวอย่าง (n = 5), วัดค่าอุณหภูมิ 3 จุด (d = 3)
"""
# n = 5, d = 3
X = torch.tensor([
    [23.0, 24.1, 22.5],
    [22.8, 24.0, 22.3],
    [23.5, 25.2, 23.0],
    [24.0, 24.8, 23.2],
    [23.2, 24.6, 22.8]
])
X

tensor([[23.0000, 24.1000, 22.5000],
        [22.8000, 24.0000, 22.3000],
        [23.5000, 25.2000, 23.0000],
        [24.0000, 24.8000, 23.2000],
        [23.2000, 24.6000, 22.8000]])

In [11]:
"""
ตัวอย่างที่ 4: Text embedding – 2 คำ แต่ละคำมีเวกเตอร์ฝังขนาด 5 (d = 5)
"""
# n = 2, d = 5
X = torch.tensor([
    [0.1, 0.3, 0.5, 0.7, 0.9],
    [0.0, 0.2, 0.4, 0.6, 0.8]
])
X

tensor([[0.1000, 0.3000, 0.5000, 0.7000, 0.9000],
        [0.0000, 0.2000, 0.4000, 0.6000, 0.8000]])

In [14]:
"""
 ตัวอย่างที่ 5: ข้อมูลป้อนเข้า MLP – 10 ตัวอย่าง, แต่ละตัวอย่างมี 100 ฟีเจอร์
"""
# n = 10, d = 100
X = torch.randn(10, 100)
# X